// P2-05: real HTTP integration tests against a live, isolated Worker instance - not just
// source/HTML-text regression pinning (see tests/rendered-html.test.mjs for that). The API
// routes read their D1/R2 bindings via `import { env } from "cloudflare:workers"`, which only
// exists inside an actual Workers/Miniflare runtime - a bare `node --test` import of the built
// worker (as rendered-html.test.mjs does for the unauthenticated landing page) cannot provide
// real bindings. So this file spawns a real `wrangler dev` process against a throwaway,
// completely isolated local D1 (never production, never the developer's own `npm run dev`
// database) and drives it with real fetch() requests, the same way a browser or the offline
// sync queue would.
import assert from "node:assert/strict";
import { spawn, spawnSync } from "node:child_process";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { setTimeout as delay } from "node:timers/promises";
import { after, before, test } from "node:test";

const PORT = 18787;
const BASE = `http://127.0.0.1:${PORT}`;
const repoRoot = fileURLToPath(new URL("../", import.meta.url));

let child;
let persistDir;

before(async () => {
  persistDir = mkdtempSync(join(tmpdir(), "menahel-avoda-integration-"));
  // Windows can't spawn a .cmd file directly without a shell (EINVAL) - node_modules/.bin's
  // wrangler shim is a .cmd there. shell:true is safe here: every argument is either a hardcoded
  // constant or generated by this file (PORT, persistDir from mkdtempSync), never external input.
  const wranglerBin = join(repoRoot, "node_modules", ".bin", process.platform === "win32" ? "wrangler.cmd" : "wrangler");
  // `wrangler dev` itself spawns further child processes (a proxy + the actual workerd
  // runtime) - a plain child.kill() only signals the immediate child and leaks the rest as
  // orphans (confirmed while developing this test: repeated runs left workerd.exe processes
  // running indefinitely). detached:true (POSIX: new process group, killed via the negative
  // PID) / taskkill /T (Windows: kill the whole tree) in the after() hook below are both
  // needed to actually clean up.
  child = spawn(
    wranglerBin,
    ["dev", "--config", "dist/server/wrangler.json", "--port", String(PORT), "--ip", "127.0.0.1", "--persist-to", persistDir, "--log-level", "error"],
    { cwd: repoRoot, stdio: ["ignore", "ignore", "ignore"], shell: process.platform === "win32", detached: process.platform !== "win32" },
  );
  child.on("error", () => {}); // surfaced via the readiness timeout below instead
  const deadline = Date.now() + 30_000;
  let ready = false;
  while (!ready && Date.now() < deadline) {
    try {
      const response = await fetch(`${BASE}/`, { headers: { accept: "text/html" } });
      ready = response.status === 200;
    } catch {
      // server not listening yet
    }
    if (!ready) await delay(500);
  }
  if (!ready) throw new Error("wrangler dev did not become ready within 30s");
});

after(async () => {
  if (child && !child.killed && child.pid) {
    if (process.platform === "win32") {
      // /T kills the whole process tree (wrangler's proxy + the workerd runtime it spawns),
      // not just the immediate .cmd shim - plain child.kill() left both running indefinitely.
      spawnSync("taskkill", ["/pid", String(child.pid), "/T", "/F"], { stdio: "ignore" });
    } else {
      // detached:true above made this process the leader of its own group; killing the
      // negative PID signals the whole group instead of just the immediate child.
      try { process.kill(-child.pid, "SIGKILL"); } catch { /* already exited */ }
    }
  }
  // Give the OS a moment to release its file handles on persistDir before removing it.
  await delay(300);
  if (persistDir) { try { rmSync(persistDir, { recursive: true, force: true }); } catch { /* best effort - OS temp dir gets swept regardless */ } }
});

async function register(email, password = "IntegrationTest1234!") {
  const form = new FormData();
  form.set("action", "register");
  form.set("firstName", "Test");
  form.set("lastName", "Account");
  form.set("phone", "0500000000");
  form.set("email", email);
  form.set("password", password);
  form.set("confirmPassword", password);
  const response = await fetch(`${BASE}/api/auth`, { method: "POST", body: form });
  assert.equal(response.status, 201, `register(${email}) failed: ${await response.text()}`);
  const cookie = response.headers.get("set-cookie");
  assert.match(cookie ?? "", /^__Host-menahel_session=/, "register() must set the session cookie");
  return cookie.split(";")[0];
}

async function action(cookie, body) {
  return fetch(`${BASE}/api/state`, {
    method: "POST",
    headers: { "content-type": "application/json", cookie },
    body: JSON.stringify(body),
  });
}

async function state(cookie) {
  const response = await fetch(`${BASE}/api/state`, { headers: { cookie } });
  const body = await readBody(response);
  assert.equal(response.status, 200, JSON.stringify(body));
  return body;
}

// Read a response body exactly once (a Response's body stream can only be consumed a single
// time) and reuse the parsed value both for pass/fail assertion messages and for whatever the
// caller needs next - unlike calling both `.text()` (for a failure message) and `.json()`
// (for the data) on the same response, which throws "Body is unusable" the moment both run.
async function readBody(response) {
  const text = await response.text();
  try { return JSON.parse(text); } catch { return text; }
}

test("cross-business isolation, role enforcement, and the P2-02/409 conflict path - against a live server", async () => {
  const stamp = Date.now();
  const cookieA = await register(`integration-a-${stamp}@example.com`);
  const cookieB = await register(`integration-b-${stamp}@example.com`);

  // --- (a) cross-business data isolation ---
  const addClientRes = await action(cookieA, { action: "addClient", id: crypto.randomUUID(), name: "Client A", address: "1 Test St", email: "client-a@example.com" });
  const stateA = await readBody(addClientRes);
  assert.equal(addClientRes.status, 200, JSON.stringify(stateA));
  const clientId = stateA.clients.find((c) => c.name === "Client A").id;

  const stateB = await state(cookieB);
  assert.ok(!stateB.clients.some((c) => c.id === clientId), "business B must not see business A's client in its own state");

  const crossUpdate = await action(cookieB, { action: "updateClient", id: clientId, name: "Hijacked", address: "x", email: "x@example.com" });
  assert.equal(crossUpdate.status, 400, "business B must not be able to mutate business A's client (scoped WHERE business_id = ? finds no row -> 400 'not found', not a 200)");

  // --- (b) manager-only action rejected for an employee session ---
  await action(cookieA, { action: "setAccountMode", accountMode: "employer" });
  const employeeEmail = `integration-employee-${stamp}@example.com`;
  const employeeId = crypto.randomUUID();
  const addEmployeeRes = await action(cookieA, { action: "addEmployee", id: employeeId, name: "Employee One", email: employeeEmail, hourlyCost: 10 });
  assert.equal(addEmployeeRes.status, 200, JSON.stringify(await readBody(addEmployeeRes)));
  const inviteRes = await action(cookieA, { action: "createEmployeeInvitation", id: employeeId });
  const inviteState = await readBody(inviteRes);
  assert.equal(inviteRes.status, 200, JSON.stringify(inviteState));
  const invitationToken = inviteState.employees.find((e) => e.id === employeeId)?.invitationToken;
  assert.ok(invitationToken, "createEmployeeInvitation must expose a token for the manager to send");

  const cookieEmployee = await register(employeeEmail);
  const acceptRes = await fetch(`${BASE}/api/state`, {
    method: "POST",
    headers: { "content-type": "application/json", cookie: cookieEmployee },
    body: JSON.stringify({ action: "acceptInvitation", token: invitationToken }),
  });
  assert.equal(acceptRes.status, 200, JSON.stringify(await readBody(acceptRes)));

  const employeeAddClient = await action(cookieEmployee, { action: "addClient", id: crypto.randomUUID(), name: "Should Be Blocked", address: "x", email: "x@example.com" });
  assert.equal(employeeAddClient.status, 403, "a manager-only action (addClient) must be rejected for an employee session");

  // --- (c) the P2-02 conflict path: server must return a structured 409, real request/response ---
  const originalUpdatedAt = stateA.clients.find((c) => c.id === clientId).updatedAt;
  // D1's CURRENT_TIMESTAMP has 1-second resolution - without this, `first` below could complete
  // within the same second as the client's creation, leaving updated_at unchanged and making the
  // "stale" expectedUpdatedAt used for secondAttempt indistinguishable from the current value.
  await delay(1100);
  const first = await action(cookieA, { action: "updateClient", id: clientId, name: "Client A v2", address: "1 Test St", email: "client-a@example.com", expectedUpdatedAt: originalUpdatedAt });
  assert.equal(first.status, 200, JSON.stringify(await readBody(first)));
  const secondAttempt = await action(cookieA, {
    action: "updateClient", id: clientId, name: "Client A - stale concurrent edit", address: "1 Test St", email: "client-a@example.com",
    expectedUpdatedAt: originalUpdatedAt, // deliberately stale: the pre-`first` value, simulating a second concurrent editor
  });
  const conflictBody = await readBody(secondAttempt);
  assert.equal(secondAttempt.status, 409, `a stale expectedUpdatedAt must be rejected as a version conflict: ${JSON.stringify(conflictBody)}`);
  assert.equal(conflictBody.conflict?.entity, "client");
  assert.ok(conflictBody.error, "a 409 conflict must include a human-readable error message the client can surface (P2-02)");
});
